[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
cache_path  = 'forge-cache'
gas_reports = ["*"]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_KEY}" }

# See more config options https://book.getfoundry.sh/reference/config.html
