[profile.default]
src = 'src'
out = 'out'
libs = ["node_modules", "lib"]
remappings = [
    '@decentral.ee/=node_modules/@decentral.ee/',
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@superfluid-finance/=node_modules/@superfluid-finance/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
]
test = 'test'
cache_path  = 'forge-cache'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config